# Generated by Django 5.1.1 on 2024-12-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0003_registration_business_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='founderregisration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('business', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profilepic/')),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
