# Generated by Django 5.1.4 on 2025-01-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0005_investorregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorregistration',
            name='bio',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investorregistration',
            name='interested_sectors',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='founderregisration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='investorregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
