# Generated by Django 5.1.1 on 2025-01-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0006_investorregistration_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderregisration',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investorregistration',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investorregistration',
            name='interested_sectors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
