# Generated by Django 5.1 on 2025-01-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0009_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='stockprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='totalstock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
