# Generated by Django 5.1.1 on 2025-01-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0010_startup_stockprice_startup_totalstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundapp.founderregisration'),
        ),
    ]
