# Generated by Django 5.1.1 on 2025-01-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0011_alter_startup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_stocks', models.IntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundapp.investorregistration')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundapp.startup')),
            ],
        ),
    ]
