# Generated by Django 5.1.1 on 2025-01-27 10:30

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone  # Correct import for timezone.now

class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0012_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investor',
        ),
        migrations.AddField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fundapp.investorregistration'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('razorpay_order_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundapp.investorregistration')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundapp.startup')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fundapp.payment'),
            preserve_default=False,
        ),
    ]
