# Generated by Django 5.1.1 on 2025-02-02 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0013_remove_investment_investor_investment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundapp.investment')),
            ],
        ),
    ]
