# Generated by Django 5.1.1 on 2025-02-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0014_paymen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymen',
            name='transaction_id',
        ),
    ]
