# Generated by Django 5.1.1 on 2025-02-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0015_remove_paymen_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.CharField(max_length=255)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=50)),
            ],
        ),
    ]
